version: "3.9"

services:

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: jobqueue-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 60s

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    container_name: jobqueue-api
    ports:
      - "${API_HTTP_PORT}:${API_HTTP_PORT}"
      - "${API_GRPC_PORT}:${API_GRPC_PORT}"
    environment:
      RABBITMQ_URL: amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672/
      RABBITMQ_QUEUE: ${RABBITMQ_QUEUE}
      RABBITMQ_DLQ: ${RABBITMQ_DLQ}
      API_HTTP_PORT: ${API_HTTP_PORT}
      API_GRPC_PORT: ${API_GRPC_PORT}
    depends_on:
      rabbitmq:
        condition: service_healthy

  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.worker
    container_name: jobqueue-worker
    ports:
      - "${WORKER_DISPATCH_PORT}:${WORKER_DISPATCH_PORT}"
    environment:
      RABBITMQ_URL: amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672/
      RABBITMQ_QUEUE: ${RABBITMQ_QUEUE}
      RABBITMQ_DLQ: ${RABBITMQ_DLQ}
      API_GRPC_ADDR: api:${API_GRPC_PORT}
      WORKER_HOST: worker
      WORKER_DISPATCH_PORT: ${WORKER_DISPATCH_PORT}
    depends_on:
      rabbitmq:
        condition: service_healthy
      api:
        condition: service_started

volumes:
  rabbitmq_data: