version: "3.9"

services:

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: jobqueue-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    container_name: jobqueue-api
    ports:
      - "${API_HTTP_PORT}:${API_HTTP_PORT}"
      - "${API_GRPC_PORT}:${API_GRPC_PORT}"
    environment:
      RABBITMQ_URL: ${RABBITMQ_URL}
      RABBITMQ_QUEUE: ${RABBITMQ_QUEUE}
      RABBITMQ_DLQ: ${RABBITMQ_DLQ}
      API_HTTP_PORT: ${API_HTTP_PORT}
      API_GRPC_PORT: ${API_GRPC_PORT}
    depends_on:
      rabbitmq:
        condition: service_healthy

  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.worker
    container_name: jobqueue-worker
    ports:
      - "${WORKER_DISPATCH_PORT}:${WORKER_DISPATCH_PORT}"
    environment:
      RABBITMQ_URL: ${RABBITMQ_URL}
      RABBITMQ_QUEUE: ${RABBITMQ_QUEUE}
      RABBITMQ_DLQ: ${RABBITMQ_DLQ}
      API_GRPC_ADDR: ${DOCKER_API_GRPC_ADDR}
      WORKER_DISPATCH_PORT: ${WORKER_DISPATCH_PORT}
    depends_on:
      - api