FROM golang:1.24-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o worker ./cmd/worker/worker_main/main.go

FROM alpine:3.19
WORKDIR /app
COPY --from=builder /app/worker .
EXPOSE 9001
CMD ["./worker"]